require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CotizacionesController do

  def mock_cotizacion(stubs={})
    @mock_cotizacion ||= mock_model(Cotizacion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cotizaciones as @cotizaciones" do
      Cotizacion.stub(:all) { [mock_cotizacion] }
      get :index
      assigns(:cotizaciones).should eq([mock_cotizacion])
    end
  end

  describe "GET show" do
    it "assigns the requested cotizacion as @cotizacion" do
      Cotizacion.stub(:find).with("37") { mock_cotizacion }
      get :show, :id => "37"
      assigns(:cotizacion).should be(mock_cotizacion)
    end
  end

  describe "GET new" do
    it "assigns a new cotizacion as @cotizacion" do
      Cotizacion.stub(:new) { mock_cotizacion }
      get :new
      assigns(:cotizacion).should be(mock_cotizacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested cotizacion as @cotizacion" do
      Cotizacion.stub(:find).with("37") { mock_cotizacion }
      get :edit, :id => "37"
      assigns(:cotizacion).should be(mock_cotizacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cotizacion as @cotizacion" do
        Cotizacion.stub(:new).with({'these' => 'params'}) { mock_cotizacion(:save => true) }
        post :create, :cotizacion => {'these' => 'params'}
        assigns(:cotizacion).should be(mock_cotizacion)
      end

      it "redirects to the created cotizacion" do
        Cotizacion.stub(:new) { mock_cotizacion(:save => true) }
        post :create, :cotizacion => {}
        response.should redirect_to(cotizacion_url(mock_cotizacion))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cotizacion as @cotizacion" do
        Cotizacion.stub(:new).with({'these' => 'params'}) { mock_cotizacion(:save => false) }
        post :create, :cotizacion => {'these' => 'params'}
        assigns(:cotizacion).should be(mock_cotizacion)
      end

      it "re-renders the 'new' template" do
        Cotizacion.stub(:new) { mock_cotizacion(:save => false) }
        post :create, :cotizacion => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cotizacion" do
        Cotizacion.stub(:find).with("37") { mock_cotizacion }
        mock_cotizacion.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cotizacion => {'these' => 'params'}
      end

      it "assigns the requested cotizacion as @cotizacion" do
        Cotizacion.stub(:find) { mock_cotizacion(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cotizacion).should be(mock_cotizacion)
      end

      it "redirects to the cotizacion" do
        Cotizacion.stub(:find) { mock_cotizacion(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cotizacion_url(mock_cotizacion))
      end
    end

    describe "with invalid params" do
      it "assigns the cotizacion as @cotizacion" do
        Cotizacion.stub(:find) { mock_cotizacion(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cotizacion).should be(mock_cotizacion)
      end

      it "re-renders the 'edit' template" do
        Cotizacion.stub(:find) { mock_cotizacion(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cotizacion" do
      Cotizacion.stub(:find).with("37") { mock_cotizacion }
      mock_cotizacion.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cotizaciones list" do
      Cotizacion.stub(:find) { mock_cotizacion }
      delete :destroy, :id => "1"
      response.should redirect_to(cotizaciones_url)
    end
  end

end
