require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EntidadesController do

  def mock_entidad(stubs={})
    @mock_entidad ||= mock_model(Entidad, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all entidades as @entidades" do
      Entidad.stub(:all) { [mock_entidad] }
      get :index
      assigns(:entidades).should eq([mock_entidad])
    end
  end

  describe "GET show" do
    it "assigns the requested entidad as @entidad" do
      Entidad.stub(:find).with("37") { mock_entidad }
      get :show, :id => "37"
      assigns(:entidad).should be(mock_entidad)
    end
  end

  describe "GET new" do
    it "assigns a new entidad as @entidad" do
      Entidad.stub(:new) { mock_entidad }
      get :new
      assigns(:entidad).should be(mock_entidad)
    end
  end

  describe "GET edit" do
    it "assigns the requested entidad as @entidad" do
      Entidad.stub(:find).with("37") { mock_entidad }
      get :edit, :id => "37"
      assigns(:entidad).should be(mock_entidad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created entidad as @entidad" do
        Entidad.stub(:new).with({'these' => 'params'}) { mock_entidad(:save => true) }
        post :create, :entidad => {'these' => 'params'}
        assigns(:entidad).should be(mock_entidad)
      end

      it "redirects to the created entidad" do
        Entidad.stub(:new) { mock_entidad(:save => true) }
        post :create, :entidad => {}
        response.should redirect_to(entidad_url(mock_entidad))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entidad as @entidad" do
        Entidad.stub(:new).with({'these' => 'params'}) { mock_entidad(:save => false) }
        post :create, :entidad => {'these' => 'params'}
        assigns(:entidad).should be(mock_entidad)
      end

      it "re-renders the 'new' template" do
        Entidad.stub(:new) { mock_entidad(:save => false) }
        post :create, :entidad => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entidad" do
        Entidad.stub(:find).with("37") { mock_entidad }
        mock_entidad.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :entidad => {'these' => 'params'}
      end

      it "assigns the requested entidad as @entidad" do
        Entidad.stub(:find) { mock_entidad(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:entidad).should be(mock_entidad)
      end

      it "redirects to the entidad" do
        Entidad.stub(:find) { mock_entidad(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(entidad_url(mock_entidad))
      end
    end

    describe "with invalid params" do
      it "assigns the entidad as @entidad" do
        Entidad.stub(:find) { mock_entidad(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:entidad).should be(mock_entidad)
      end

      it "re-renders the 'edit' template" do
        Entidad.stub(:find) { mock_entidad(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entidad" do
      Entidad.stub(:find).with("37") { mock_entidad }
      mock_entidad.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the entidades list" do
      Entidad.stub(:find) { mock_entidad }
      delete :destroy, :id => "1"
      response.should redirect_to(entidades_url)
    end
  end

end
