require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MovimientosController do

  def mock_movimiento(stubs={})
    @mock_movimiento ||= mock_model(Movimiento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all movimientos as @movimientos" do
      Movimiento.stub(:all) { [mock_movimiento] }
      get :index
      assigns(:movimientos).should eq([mock_movimiento])
    end
  end

  describe "GET show" do
    it "assigns the requested movimiento as @movimiento" do
      Movimiento.stub(:find).with("37") { mock_movimiento }
      get :show, :id => "37"
      assigns(:movimiento).should be(mock_movimiento)
    end
  end

  describe "GET new" do
    it "assigns a new movimiento as @movimiento" do
      Movimiento.stub(:new) { mock_movimiento }
      get :new
      assigns(:movimiento).should be(mock_movimiento)
    end
  end

  describe "GET edit" do
    it "assigns the requested movimiento as @movimiento" do
      Movimiento.stub(:find).with("37") { mock_movimiento }
      get :edit, :id => "37"
      assigns(:movimiento).should be(mock_movimiento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created movimiento as @movimiento" do
        Movimiento.stub(:new).with({'these' => 'params'}) { mock_movimiento(:save => true) }
        post :create, :movimiento => {'these' => 'params'}
        assigns(:movimiento).should be(mock_movimiento)
      end

      it "redirects to the created movimiento" do
        Movimiento.stub(:new) { mock_movimiento(:save => true) }
        post :create, :movimiento => {}
        response.should redirect_to(movimiento_url(mock_movimiento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved movimiento as @movimiento" do
        Movimiento.stub(:new).with({'these' => 'params'}) { mock_movimiento(:save => false) }
        post :create, :movimiento => {'these' => 'params'}
        assigns(:movimiento).should be(mock_movimiento)
      end

      it "re-renders the 'new' template" do
        Movimiento.stub(:new) { mock_movimiento(:save => false) }
        post :create, :movimiento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested movimiento" do
        Movimiento.stub(:find).with("37") { mock_movimiento }
        mock_movimiento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :movimiento => {'these' => 'params'}
      end

      it "assigns the requested movimiento as @movimiento" do
        Movimiento.stub(:find) { mock_movimiento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:movimiento).should be(mock_movimiento)
      end

      it "redirects to the movimiento" do
        Movimiento.stub(:find) { mock_movimiento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(movimiento_url(mock_movimiento))
      end
    end

    describe "with invalid params" do
      it "assigns the movimiento as @movimiento" do
        Movimiento.stub(:find) { mock_movimiento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:movimiento).should be(mock_movimiento)
      end

      it "re-renders the 'edit' template" do
        Movimiento.stub(:find) { mock_movimiento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested movimiento" do
      Movimiento.stub(:find).with("37") { mock_movimiento }
      mock_movimiento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the movimientos list" do
      Movimiento.stub(:find) { mock_movimiento }
      delete :destroy, :id => "1"
      response.should redirect_to(movimientos_url)
    end
  end

end
