require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OperadorasController do

  def mock_operadora(stubs={})
    @mock_operadora ||= mock_model(Operadora, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all operadoras as @operadoras" do
      Operadora.stub(:all) { [mock_operadora] }
      get :index
      assigns(:operadoras).should eq([mock_operadora])
    end
  end

  describe "GET show" do
    it "assigns the requested operadora as @operadora" do
      Operadora.stub(:find).with("37") { mock_operadora }
      get :show, :id => "37"
      assigns(:operadora).should be(mock_operadora)
    end
  end

  describe "GET new" do
    it "assigns a new operadora as @operadora" do
      Operadora.stub(:new) { mock_operadora }
      get :new
      assigns(:operadora).should be(mock_operadora)
    end
  end

  describe "GET edit" do
    it "assigns the requested operadora as @operadora" do
      Operadora.stub(:find).with("37") { mock_operadora }
      get :edit, :id => "37"
      assigns(:operadora).should be(mock_operadora)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created operadora as @operadora" do
        Operadora.stub(:new).with({'these' => 'params'}) { mock_operadora(:save => true) }
        post :create, :operadora => {'these' => 'params'}
        assigns(:operadora).should be(mock_operadora)
      end

      it "redirects to the created operadora" do
        Operadora.stub(:new) { mock_operadora(:save => true) }
        post :create, :operadora => {}
        response.should redirect_to(operadora_url(mock_operadora))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved operadora as @operadora" do
        Operadora.stub(:new).with({'these' => 'params'}) { mock_operadora(:save => false) }
        post :create, :operadora => {'these' => 'params'}
        assigns(:operadora).should be(mock_operadora)
      end

      it "re-renders the 'new' template" do
        Operadora.stub(:new) { mock_operadora(:save => false) }
        post :create, :operadora => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested operadora" do
        Operadora.stub(:find).with("37") { mock_operadora }
        mock_operadora.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :operadora => {'these' => 'params'}
      end

      it "assigns the requested operadora as @operadora" do
        Operadora.stub(:find) { mock_operadora(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:operadora).should be(mock_operadora)
      end

      it "redirects to the operadora" do
        Operadora.stub(:find) { mock_operadora(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(operadora_url(mock_operadora))
      end
    end

    describe "with invalid params" do
      it "assigns the operadora as @operadora" do
        Operadora.stub(:find) { mock_operadora(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:operadora).should be(mock_operadora)
      end

      it "re-renders the 'edit' template" do
        Operadora.stub(:find) { mock_operadora(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested operadora" do
      Operadora.stub(:find).with("37") { mock_operadora }
      mock_operadora.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the operadoras list" do
      Operadora.stub(:find) { mock_operadora }
      delete :destroy, :id => "1"
      response.should redirect_to(operadoras_url)
    end
  end

end
