require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PagosController do

  fixtures :reservas, :tdepositos, :entidads

  def valid_attributes
    { :fecha => "25/10/1985", :entidad_id => Fixtures.identify(:litoraltur),
    :tdeposito_id => Fixtures.identify(:deposito), :reserva_id => Fixtures.identify(:costa_magica),
    :monto => "5000 USD" }
  end

  describe "GET index" do
    it "assigns all pagos as @pagos" do
      pago = Pago.create! valid_attributes
      get :index
      assigns(:pagos).should eq([pago])
    end
  end

  describe "GET show" do
    it "assigns the requested pago as @pago" do
      pago = Pago.create! valid_attributes
      get :show, :id => pago.id.to_s
      assigns(:pago).should eq(pago)
    end
  end

  describe "GET new" do
    it "assigns a new pago as @pago" do
      get :new
      assigns(:pago).should be_a_new(Pago)
    end
  end

  describe "GET edit" do
    it "assigns the requested pago as @pago" do
      pago = Pago.create! valid_attributes
      get :edit, :id => pago.id.to_s
      assigns(:pago).should eq(pago)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pago" do
        expect {
          post :create, :pago => valid_attributes
        }.to change(Pago, :count).by(1)
      end

      it "assigns a newly created pago as @pago" do
        post :create, :pago => valid_attributes
        assigns(:pago).should be_a(Pago)
        assigns(:pago).should be_persisted
      end

      it "redirects to the created pago" do
        post :create, :pago => valid_attributes
        response.should redirect_to(Pago.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pago as @pago" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pago.any_instance.stub(:save).and_return(false)
        post :create, :pago => {}
        assigns(:pago).should be_a_new(Pago)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pago.any_instance.stub(:save).and_return(false)
        post :create, :pago => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pago" do
        pago = Pago.create! valid_attributes
        # Assuming there are no other pagos in the database, this
        # specifies that the Pago created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pago.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pago.id, :pago => {'these' => 'params'}
      end

      it "assigns the requested pago as @pago" do
        pago = Pago.create! valid_attributes
        put :update, :id => pago.id, :pago => valid_attributes
        assigns(:pago).should eq(pago)
      end

      it "redirects to the pago" do
        pago = Pago.create! valid_attributes
        put :update, :id => pago.id, :pago => valid_attributes
        response.should redirect_to(pago)
      end
    end

    describe "with invalid params" do
      it "assigns the pago as @pago" do
        pago = Pago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pago.any_instance.stub(:save).and_return(false)
        put :update, :id => pago.id.to_s, :pago => {}
        assigns(:pago).should eq(pago)
      end

      it "re-renders the 'edit' template" do
        pago = Pago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pago.any_instance.stub(:save).and_return(false)
        put :update, :id => pago.id.to_s, :pago => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pago" do
      pago = Pago.create! valid_attributes
      expect {
        delete :destroy, :id => pago.id.to_s
      }.to change(Pago, :count).by(-1)
    end

    it "redirects to the pagos list" do
      pago = Pago.create! valid_attributes
      delete :destroy, :id => pago.id.to_s
      response.should redirect_to(pagos_url)
    end
  end

  context "entrando desde reserva" do
    it "get index con reserva id tanto."
    describe "GET index" do
      it "todos los pagos de la reserva selecciona as @pagos" do
        get :index, :reserva_id => Fixtures.identify(:grand_celebration)
        assigns(:pagos).should eq(reservas(:grand_celebration).pagos)
      end
    end
  end
end
