require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PasajerosController do

  def mock_pasajero(stubs={})
    @mock_pasajero ||= mock_model(Pasajero, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all pasajeros as @pasajeros" do
      Pasajero.stub(:all) { [mock_pasajero] }
      get :index
      assigns(:pasajeros).should eq([mock_pasajero])
    end
  end

  describe "GET show" do
    it "assigns the requested pasajero as @pasajero" do
      Pasajero.stub(:find).with("37") { mock_pasajero }
      get :show, :id => "37"
      assigns(:pasajero).should be(mock_pasajero)
    end
  end

  describe "GET new" do
    it "assigns a new pasajero as @pasajero" do
      Pasajero.stub(:new) { mock_pasajero }
      get :new
      assigns(:pasajero).should be(mock_pasajero)
    end
  end

  describe "GET edit" do
    it "assigns the requested pasajero as @pasajero" do
      Pasajero.stub(:find).with("37") { mock_pasajero }
      get :edit, :id => "37"
      assigns(:pasajero).should be(mock_pasajero)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created pasajero as @pasajero" do
        Pasajero.stub(:new).with({'these' => 'params'}) { mock_pasajero(:save => true) }
        post :create, :pasajero => {'these' => 'params'}
        assigns(:pasajero).should be(mock_pasajero)
      end

      it "redirects to the created pasajero" do
        Pasajero.stub(:new) { mock_pasajero(:save => true) }
        post :create, :pasajero => {}
        response.should redirect_to(pasajero_url(mock_pasajero))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pasajero as @pasajero" do
        Pasajero.stub(:new).with({'these' => 'params'}) { mock_pasajero(:save => false) }
        post :create, :pasajero => {'these' => 'params'}
        assigns(:pasajero).should be(mock_pasajero)
      end

      it "re-renders the 'new' template" do
        Pasajero.stub(:new) { mock_pasajero(:save => false) }
        post :create, :pasajero => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pasajero" do
        Pasajero.stub(:find).with("37") { mock_pasajero }
        mock_pasajero.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :pasajero => {'these' => 'params'}
      end

      it "assigns the requested pasajero as @pasajero" do
        Pasajero.stub(:find) { mock_pasajero(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:pasajero).should be(mock_pasajero)
      end

      it "redirects to the pasajero" do
        Pasajero.stub(:find) { mock_pasajero(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(pasajero_url(mock_pasajero))
      end
    end

    describe "with invalid params" do
      it "assigns the pasajero as @pasajero" do
        Pasajero.stub(:find) { mock_pasajero(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:pasajero).should be(mock_pasajero)
      end

      it "re-renders the 'edit' template" do
        Pasajero.stub(:find) { mock_pasajero(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pasajero" do
      Pasajero.stub(:find).with("37") { mock_pasajero }
      mock_pasajero.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the pasajeros list" do
      Pasajero.stub(:find) { mock_pasajero }
      delete :destroy, :id => "1"
      response.should redirect_to(pasajeros_url)
    end
  end

end
