require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TarifasController do

  def mock_tarifa(stubs={})
    @mock_tarifa ||= mock_model(Tarifa, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tarifas as @tarifas" do
      Tarifa.stub(:all) { [mock_tarifa] }
      get :index
      #assigns(:tarifas).should eq([mock_tarifa])
      assigns(:tarifas).should eq([])
    end
  end

  describe "GET show" do
    it "assigns the requested tarifa as @tarifa" do
      Tarifa.stub(:find).with("37") { mock_tarifa }
      get :show, :id => "37"
      assigns(:tarifa).should be(mock_tarifa)
    end
  end

  describe "GET new" do
    it "assigns a new tarifa as @tarifa" do
      Tarifa.stub(:new) { mock_tarifa }
      get :new
      assigns(:tarifa).should be(mock_tarifa)
    end
  end

  describe "GET edit" do
    it "assigns the requested tarifa as @tarifa" do
      Tarifa.stub(:find).with("37") { mock_tarifa }
      get :edit, :id => "37"
      assigns(:tarifa).should be(mock_tarifa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tarifa as @tarifa" do
        Tarifa.stub(:new).with({'these' => 'params'}) { mock_tarifa(:save => true) }
        post :create, :tarifa => {'these' => 'params'}
        assigns(:tarifa).should be(mock_tarifa)
      end

      it "redirects to the created tarifa" do
        Tarifa.stub(:new) { mock_tarifa(:save => true) }
        post :create, :tarifa => {}
        response.should redirect_to(:controller =>:tarifas,:action=>'show',:format=>:js,:id=>mock_tarifa.id)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tarifa as @tarifa" do
        Tarifa.stub(:new).with({'these' => 'params'}) { mock_tarifa(:save => false) }
        post :create, :tarifa => {'these' => 'params'}
        assigns(:tarifa).should be(mock_tarifa)
      end

      it "re-renders the 'new' template" do
        Tarifa.stub(:new) { mock_tarifa(:save => false) }
        post :create, :tarifa => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tarifa" do
        Tarifa.stub(:find).with("37") { mock_tarifa }
        mock_tarifa.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tarifa => {'these' => 'params'}
      end

      it "assigns the requested tarifa as @tarifa" do
        Tarifa.stub(:find) { mock_tarifa(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tarifa).should be(mock_tarifa)
      end

      it "redirects to the tarifa" do
        Tarifa.stub(:find) { mock_tarifa(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(:controller =>:tarifas,:action=>'show',:format=>:js,:id=>mock_tarifa.id)
      end
    end

    describe "with invalid params" do
      it "assigns the tarifa as @tarifa" do
        Tarifa.stub(:find) { mock_tarifa(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tarifa).should be(mock_tarifa)
      end

      it "re-renders the 'edit' template" do
        Tarifa.stub(:find) { mock_tarifa(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tarifa" do
      Tarifa.stub(:find).with("37") { mock_tarifa }
      mock_tarifa.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    #it "redirects to the tarifas list" do
    #  Tarifa.stub(:find) { mock_tarifa }
    #  delete :destroy, :id => "1"
    #  response.should redirect_to(tarifas_url)
    #end
  end

end
